// Seed data for Food Compass — ~20 recipes across 6 categories

export const SEED_RECIPES = [
  // ===== BREAKFAST =====
  {
    name: 'Classic French Toast',
    category: 'Breakfast',
    cookingTime: 15,
    difficulty: 'Easy',
    description: 'Golden, crispy French toast with a hint of cinnamon and vanilla. A perfect start to your morning.',
    servings: 2,
    imageColor: '#E8A87C',
    ingredients: [
      { name: 'Bread slices', quantity: '4 slices', isRequired: 1, alternatives: null },
      { name: 'Eggs', quantity: '2', isRequired: 1, alternatives: null },
      { name: 'Milk', quantity: '1/4 cup', isRequired: 1, alternatives: 'Almond milk, Oat milk' },
      { name: 'Cinnamon powder', quantity: '1/2 tsp', isRequired: 0, alternatives: null },
      { name: 'Vanilla extract', quantity: '1/2 tsp', isRequired: 0, alternatives: null },
      { name: 'Butter', quantity: '2 tbsp', isRequired: 1, alternatives: 'Oil, Ghee' },
      { name: 'Sugar', quantity: '1 tbsp', isRequired: 0, alternatives: 'Honey, Maple syrup' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Crack eggs into a shallow bowl and whisk well.', duration: null },
      { stepNumber: 2, instruction: 'Add milk, cinnamon, vanilla extract, and sugar. Mix until combined.', duration: null },
      { stepNumber: 3, instruction: 'Heat butter in a non-stick pan over medium heat.', duration: 1 },
      { stepNumber: 4, instruction: 'Dip each bread slice into the egg mixture, coating both sides evenly.', duration: null },
      { stepNumber: 5, instruction: 'Place the coated bread on the hot pan and cook until golden brown on one side.', duration: 3 },
      { stepNumber: 6, instruction: 'Flip and cook the other side until golden and crispy.', duration: 3 },
      { stepNumber: 7, instruction: 'Serve warm with honey, maple syrup, or fresh fruits.', duration: null },
    ],
  },
  {
    name: 'Fluffy Scrambled Eggs',
    category: 'Breakfast',
    cookingTime: 10,
    difficulty: 'Easy',
    description: 'Soft, creamy scrambled eggs cooked to perfection. Quick and nutritious breakfast.',
    servings: 2,
    imageColor: '#F6E58D',
    ingredients: [
      { name: 'Eggs', quantity: '4', isRequired: 1, alternatives: null },
      { name: 'Butter', quantity: '1 tbsp', isRequired: 1, alternatives: 'Oil, Ghee' },
      { name: 'Milk', quantity: '2 tbsp', isRequired: 0, alternatives: 'Cream' },
      { name: 'Salt', quantity: 'To taste', isRequired: 1, alternatives: null },
      { name: 'Black pepper', quantity: '1/4 tsp', isRequired: 0, alternatives: null },
      { name: 'Fresh chives', quantity: '1 tbsp chopped', isRequired: 0, alternatives: 'Spring onion' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Crack eggs into a bowl, add milk, salt, and pepper. Whisk until smooth.', duration: null },
      { stepNumber: 2, instruction: 'Melt butter in a non-stick pan over low-medium heat.', duration: 1 },
      { stepNumber: 3, instruction: 'Pour the egg mixture into the pan. Let it sit for 30 seconds.', duration: 1 },
      { stepNumber: 4, instruction: 'Gently push the eggs from the edges to the center using a spatula, creating soft folds.', duration: 2 },
      { stepNumber: 5, instruction: 'Continue folding gently until eggs are just set but still creamy — do not overcook.', duration: 2 },
      { stepNumber: 6, instruction: 'Remove from heat, garnish with chives, and serve immediately.', duration: null },
    ],
  },
  {
    name: 'Banana Oat Pancakes',
    category: 'Breakfast',
    cookingTime: 20,
    difficulty: 'Easy',
    description: 'Healthy, naturally sweet pancakes made with ripe bananas and oats. No refined flour needed!',
    servings: 2,
    imageColor: '#D4A76A',
    ingredients: [
      { name: 'Ripe bananas', quantity: '2', isRequired: 1, alternatives: null },
      { name: 'Oats', quantity: '1 cup', isRequired: 1, alternatives: 'Oat flour' },
      { name: 'Eggs', quantity: '2', isRequired: 1, alternatives: null },
      { name: 'Baking powder', quantity: '1 tsp', isRequired: 1, alternatives: null },
      { name: 'Cinnamon', quantity: '1/2 tsp', isRequired: 0, alternatives: null },
      { name: 'Honey', quantity: '1 tbsp', isRequired: 0, alternatives: 'Maple syrup, Sugar' },
      { name: 'Oil', quantity: 'For cooking', isRequired: 1, alternatives: 'Butter' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Blend oats in a blender until they become a fine flour.', duration: 1 },
      { stepNumber: 2, instruction: 'Mash bananas in a bowl until smooth.', duration: null },
      { stepNumber: 3, instruction: 'Add eggs, oat flour, baking powder, cinnamon, and honey. Mix well.', duration: null },
      { stepNumber: 4, instruction: 'Heat a lightly oiled pan over medium heat.', duration: 1 },
      { stepNumber: 5, instruction: 'Pour 1/4 cup of batter for each pancake. Cook until bubbles form on top.', duration: 3 },
      { stepNumber: 6, instruction: 'Flip and cook for another 2 minutes until golden brown.', duration: 2 },
      { stepNumber: 7, instruction: 'Repeat with remaining batter. Serve with fresh fruits and honey.', duration: null },
    ],
  },

  // ===== LUNCH =====
  {
    name: 'Chicken Fried Rice',
    category: 'Lunch',
    cookingTime: 25,
    difficulty: 'Medium',
    description: 'Savory fried rice loaded with chicken, vegetables, and soy sauce. A complete meal in one pan.',
    servings: 3,
    imageColor: '#C2956B',
    ingredients: [
      { name: 'Cooked rice', quantity: '3 cups', isRequired: 1, alternatives: null },
      { name: 'Chicken breast', quantity: '200g diced', isRequired: 1, alternatives: 'Tofu, Shrimp' },
      { name: 'Soy sauce', quantity: '2 tbsp', isRequired: 1, alternatives: 'Tamari' },
      { name: 'Garlic', quantity: '3 cloves minced', isRequired: 1, alternatives: null },
      { name: 'Eggs', quantity: '2', isRequired: 1, alternatives: null },
      { name: 'Mixed vegetables', quantity: '1 cup (carrots, peas, corn)', isRequired: 1, alternatives: null },
      { name: 'Sesame oil', quantity: '1 tsp', isRequired: 0, alternatives: null },
      { name: 'Spring onions', quantity: '2 stalks', isRequired: 0, alternatives: null },
      { name: 'Oil', quantity: '2 tbsp', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Heat oil in a large pan or wok over high heat.', duration: 1 },
      { stepNumber: 2, instruction: 'Add diced chicken and cook until golden brown and cooked through.', duration: 5 },
      { stepNumber: 3, instruction: 'Push chicken to one side. Scramble eggs on the other side of the pan.', duration: 2 },
      { stepNumber: 4, instruction: 'Add minced garlic and mixed vegetables. Stir-fry for 2 minutes.', duration: 2 },
      { stepNumber: 5, instruction: 'Add cooked rice and break up any clumps. Stir everything together.', duration: 2 },
      { stepNumber: 6, instruction: 'Pour soy sauce and sesame oil over the rice. Toss well to combine.', duration: 2 },
      { stepNumber: 7, instruction: 'Cook for another 2-3 minutes, stirring occasionally, until rice is slightly crispy.', duration: 3 },
      { stepNumber: 8, instruction: 'Garnish with sliced spring onions and serve hot.', duration: null },
    ],
  },
  {
    name: 'Veggie Wrap',
    category: 'Lunch',
    cookingTime: 15,
    difficulty: 'Easy',
    description: 'Fresh and crunchy vegetable wrap with hummus and a tangy yogurt dressing.',
    servings: 2,
    imageColor: '#7CB342',
    ingredients: [
      { name: 'Tortilla wraps', quantity: '2 large', isRequired: 1, alternatives: 'Pita bread' },
      { name: 'Hummus', quantity: '4 tbsp', isRequired: 1, alternatives: 'Cream cheese, Mayo' },
      { name: 'Lettuce', quantity: '4 leaves', isRequired: 1, alternatives: 'Spinach' },
      { name: 'Cucumber', quantity: '1 sliced', isRequired: 1, alternatives: null },
      { name: 'Tomato', quantity: '1 sliced', isRequired: 1, alternatives: null },
      { name: 'Carrot', quantity: '1 grated', isRequired: 0, alternatives: null },
      { name: 'Red onion', quantity: '1/2 sliced', isRequired: 0, alternatives: null },
      { name: 'Salt & pepper', quantity: 'To taste', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Lay the tortilla wraps flat on a clean surface.', duration: null },
      { stepNumber: 2, instruction: 'Spread 2 tablespoons of hummus evenly on each wrap.', duration: null },
      { stepNumber: 3, instruction: 'Layer lettuce leaves on top of the hummus.', duration: null },
      { stepNumber: 4, instruction: 'Add sliced cucumber, tomato, grated carrot, and red onion.', duration: null },
      { stepNumber: 5, instruction: 'Season with salt and pepper to taste.', duration: null },
      { stepNumber: 6, instruction: 'Fold the bottom edge up, then roll tightly from one side to the other.', duration: null },
      { stepNumber: 7, instruction: 'Cut diagonally in half and serve immediately.', duration: null },
    ],
  },
  {
    name: 'Spaghetti Aglio e Olio',
    category: 'Lunch',
    cookingTime: 20,
    difficulty: 'Easy',
    description: 'A classic Italian pasta dish — simple yet incredibly flavorful with garlic, olive oil, and chili flakes.',
    servings: 2,
    imageColor: '#E8C07A',
    ingredients: [
      { name: 'Spaghetti', quantity: '200g', isRequired: 1, alternatives: 'Any long pasta' },
      { name: 'Olive oil', quantity: '1/4 cup', isRequired: 1, alternatives: null },
      { name: 'Garlic', quantity: '6 cloves thinly sliced', isRequired: 1, alternatives: null },
      { name: 'Red chili flakes', quantity: '1/2 tsp', isRequired: 0, alternatives: 'Fresh red chili' },
      { name: 'Fresh parsley', quantity: '2 tbsp chopped', isRequired: 0, alternatives: 'Coriander' },
      { name: 'Salt', quantity: 'To taste', isRequired: 1, alternatives: null },
      { name: 'Parmesan cheese', quantity: '2 tbsp grated', isRequired: 0, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Boil a large pot of salted water. Cook spaghetti until al dente as per package instructions.', duration: 10 },
      { stepNumber: 2, instruction: 'While pasta cooks, heat olive oil in a large pan over low-medium heat.', duration: 1 },
      { stepNumber: 3, instruction: 'Add sliced garlic to the oil and cook slowly until golden (not brown). Add chili flakes.', duration: 3 },
      { stepNumber: 4, instruction: 'Reserve 1/2 cup of pasta water, then drain the spaghetti.', duration: null },
      { stepNumber: 5, instruction: 'Add the drained spaghetti to the garlic oil. Toss well, adding pasta water as needed for silkiness.', duration: 2 },
      { stepNumber: 6, instruction: 'Garnish with fresh parsley and parmesan. Serve immediately.', duration: null },
    ],
  },

  // ===== DINNER =====
  {
    name: 'Butter Chicken',
    category: 'Dinner',
    cookingTime: 45,
    difficulty: 'Medium',
    description: 'Rich, creamy, and aromatic butter chicken with a velvety tomato-based sauce. Restaurant quality at home.',
    servings: 4,
    imageColor: '#D4613A',
    ingredients: [
      { name: 'Chicken thighs', quantity: '500g boneless', isRequired: 1, alternatives: 'Chicken breast, Paneer' },
      { name: 'Yogurt', quantity: '1/2 cup', isRequired: 1, alternatives: null },
      { name: 'Tomato puree', quantity: '1 cup', isRequired: 1, alternatives: 'Fresh blended tomatoes' },
      { name: 'Butter', quantity: '3 tbsp', isRequired: 1, alternatives: null },
      { name: 'Cream', quantity: '1/2 cup', isRequired: 1, alternatives: 'Milk, Coconut cream' },
      { name: 'Ginger-garlic paste', quantity: '2 tbsp', isRequired: 1, alternatives: null },
      { name: 'Garam masala', quantity: '1 tsp', isRequired: 1, alternatives: null },
      { name: 'Turmeric', quantity: '1/2 tsp', isRequired: 1, alternatives: null },
      { name: 'Red chili powder', quantity: '1 tsp', isRequired: 0, alternatives: 'Paprika' },
      { name: 'Kasuri methi', quantity: '1 tsp', isRequired: 0, alternatives: null },
      { name: 'Salt', quantity: 'To taste', isRequired: 1, alternatives: null },
      { name: 'Oil', quantity: '1 tbsp', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Marinate chicken with yogurt, turmeric, red chili powder, and salt for at least 15 minutes.', duration: 15 },
      { stepNumber: 2, instruction: 'Heat oil in a pan and sear the marinated chicken pieces until golden. Set aside.', duration: 5 },
      { stepNumber: 3, instruction: 'In the same pan, melt butter. Add ginger-garlic paste and sauté for 1 minute.', duration: 2 },
      { stepNumber: 4, instruction: 'Add tomato puree and cook on medium heat until oil separates from the masala.', duration: 8 },
      { stepNumber: 5, instruction: 'Add garam masala and cook for another minute.', duration: 1 },
      { stepNumber: 6, instruction: 'Add the seared chicken pieces and stir well to coat with the sauce.', duration: null },
      { stepNumber: 7, instruction: 'Pour in the cream, mix well, and simmer on low heat for 10 minutes.', duration: 10 },
      { stepNumber: 8, instruction: 'Crush kasuri methi and sprinkle on top. Stir gently.', duration: null },
      { stepNumber: 9, instruction: 'Serve hot with naan, rice, or roti.', duration: null },
    ],
  },
  {
    name: 'Vegetable Stir-Fry',
    category: 'Dinner',
    cookingTime: 20,
    difficulty: 'Easy',
    description: 'Colorful mixed vegetables tossed in a savory soy-ginger sauce. Light, healthy, and ready in minutes.',
    servings: 2,
    imageColor: '#66BB6A',
    ingredients: [
      { name: 'Broccoli florets', quantity: '1 cup', isRequired: 1, alternatives: null },
      { name: 'Bell peppers', quantity: '1 cup sliced', isRequired: 1, alternatives: null },
      { name: 'Carrots', quantity: '1 cup julienned', isRequired: 1, alternatives: null },
      { name: 'Soy sauce', quantity: '2 tbsp', isRequired: 1, alternatives: 'Tamari' },
      { name: 'Garlic', quantity: '2 cloves minced', isRequired: 1, alternatives: null },
      { name: 'Ginger', quantity: '1 tsp grated', isRequired: 1, alternatives: null },
      { name: 'Sesame oil', quantity: '1 tbsp', isRequired: 0, alternatives: 'Vegetable oil' },
      { name: 'Cornstarch', quantity: '1 tsp dissolved in 2 tbsp water', isRequired: 0, alternatives: null },
      { name: 'Oil', quantity: '2 tbsp', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Prepare all vegetables — wash, slice, and set aside.', duration: null },
      { stepNumber: 2, instruction: 'Heat oil in a wok or large pan over high heat.', duration: 1 },
      { stepNumber: 3, instruction: 'Add garlic and ginger. Stir-fry for 30 seconds until fragrant.', duration: 1 },
      { stepNumber: 4, instruction: 'Add carrots and broccoli first (they take longer). Stir-fry for 3 minutes.', duration: 3 },
      { stepNumber: 5, instruction: 'Add bell peppers and cook for another 2 minutes — vegetables should be crisp-tender.', duration: 2 },
      { stepNumber: 6, instruction: 'Pour in soy sauce and sesame oil. Toss everything together.', duration: 1 },
      { stepNumber: 7, instruction: 'Add cornstarch slurry if you want a glossy sauce. Stir for 1 minute.', duration: 1 },
      { stepNumber: 8, instruction: 'Serve hot over steamed rice or noodles.', duration: null },
    ],
  },
  {
    name: 'Grilled Salmon',
    category: 'Dinner',
    cookingTime: 25,
    difficulty: 'Medium',
    description: 'Perfectly grilled salmon fillet with a lemon-herb butter glaze. Elegant yet effortless.',
    servings: 2,
    imageColor: '#E8907A',
    ingredients: [
      { name: 'Salmon fillets', quantity: '2 pieces', isRequired: 1, alternatives: null },
      { name: 'Olive oil', quantity: '2 tbsp', isRequired: 1, alternatives: null },
      { name: 'Lemon', quantity: '1', isRequired: 1, alternatives: null },
      { name: 'Garlic', quantity: '2 cloves minced', isRequired: 1, alternatives: null },
      { name: 'Butter', quantity: '1 tbsp', isRequired: 0, alternatives: 'Olive oil' },
      { name: 'Dried herbs', quantity: '1 tsp (oregano, thyme)', isRequired: 0, alternatives: 'Fresh herbs' },
      { name: 'Salt & pepper', quantity: 'To taste', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Pat salmon fillets dry with paper towels. Season both sides with salt, pepper, and dried herbs.', duration: null },
      { stepNumber: 2, instruction: 'Mix olive oil, minced garlic, and juice of half a lemon in a small bowl.', duration: null },
      { stepNumber: 3, instruction: 'Brush the garlic-lemon mixture generously over the salmon.', duration: null },
      { stepNumber: 4, instruction: 'Preheat a grill pan or skillet over medium-high heat.', duration: 2 },
      { stepNumber: 5, instruction: 'Place salmon skin-side up and cook for 4-5 minutes until a golden crust forms.', duration: 5 },
      { stepNumber: 6, instruction: 'Flip carefully and cook for another 3-4 minutes until fish is cooked through.', duration: 4 },
      { stepNumber: 7, instruction: 'Add a small knob of butter on top while still hot. Squeeze remaining lemon over it.', duration: null },
      { stepNumber: 8, instruction: 'Serve with steamed vegetables or a fresh salad.', duration: null },
    ],
  },

  // ===== SNACKS =====
  {
    name: 'Crispy Samosas',
    category: 'Snacks',
    cookingTime: 40,
    difficulty: 'Hard',
    description: 'Golden crispy samosas filled with spiced potato and peas. The ultimate tea-time snack.',
    servings: 8,
    imageColor: '#D4A44D',
    ingredients: [
      { name: 'All-purpose flour', quantity: '1.5 cups', isRequired: 1, alternatives: 'Wheat flour' },
      { name: 'Potatoes', quantity: '3 medium boiled & mashed', isRequired: 1, alternatives: null },
      { name: 'Green peas', quantity: '1/2 cup', isRequired: 0, alternatives: null },
      { name: 'Cumin seeds', quantity: '1 tsp', isRequired: 1, alternatives: null },
      { name: 'Garam masala', quantity: '1 tsp', isRequired: 1, alternatives: null },
      { name: 'Green chili', quantity: '2 chopped', isRequired: 0, alternatives: 'Red chili powder' },
      { name: 'Coriander leaves', quantity: '2 tbsp', isRequired: 0, alternatives: null },
      { name: 'Oil', quantity: 'For deep frying', isRequired: 1, alternatives: null },
      { name: 'Salt', quantity: 'To taste', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Make the dough: Mix flour, 2 tbsp oil, salt, and water. Knead into a firm dough. Rest for 20 minutes.', duration: 20 },
      { stepNumber: 2, instruction: 'Heat 1 tbsp oil. Add cumin seeds and let them splutter.', duration: 1 },
      { stepNumber: 3, instruction: 'Add mashed potatoes, peas, garam masala, green chili, and salt. Mix well and cook for 3 minutes.', duration: 3 },
      { stepNumber: 4, instruction: 'Add coriander leaves, mix, and let the filling cool down.', duration: null },
      { stepNumber: 5, instruction: 'Divide dough into balls. Roll each into an oval shape and cut in half to form semi-circles.', duration: null },
      { stepNumber: 6, instruction: 'Form a cone shape with each semi-circle, fill with the potato mixture, and seal the edges with water.', duration: null },
      { stepNumber: 7, instruction: 'Heat oil for deep frying over medium heat (not too hot).', duration: 3 },
      { stepNumber: 8, instruction: 'Fry samosas on medium-low heat until golden and crispy on all sides.', duration: 8 },
      { stepNumber: 9, instruction: 'Drain on paper towels. Serve hot with mint chutney or tamarind sauce.', duration: null },
    ],
  },
  {
    name: 'Guacamole & Chips',
    category: 'Snacks',
    cookingTime: 10,
    difficulty: 'Easy',
    description: 'Fresh, zesty guacamole with perfectly ripe avocados. The ultimate party dip.',
    servings: 4,
    imageColor: '#8BC34A',
    ingredients: [
      { name: 'Ripe avocados', quantity: '2', isRequired: 1, alternatives: null },
      { name: 'Lime', quantity: '1', isRequired: 1, alternatives: 'Lemon' },
      { name: 'Red onion', quantity: '1/4 finely diced', isRequired: 1, alternatives: null },
      { name: 'Tomato', quantity: '1 diced', isRequired: 1, alternatives: null },
      { name: 'Cilantro', quantity: '2 tbsp chopped', isRequired: 0, alternatives: 'Parsley' },
      { name: 'Salt', quantity: 'To taste', isRequired: 1, alternatives: null },
      { name: 'Tortilla chips', quantity: '1 bag', isRequired: 1, alternatives: 'Nachos, Pita chips' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Cut avocados in half, remove pit, and scoop the flesh into a bowl.', duration: null },
      { stepNumber: 2, instruction: 'Mash the avocado with a fork to your desired consistency (chunky or smooth).', duration: null },
      { stepNumber: 3, instruction: 'Add diced red onion, tomato, and chopped cilantro.', duration: null },
      { stepNumber: 4, instruction: 'Squeeze fresh lime juice over the mixture.', duration: null },
      { stepNumber: 5, instruction: 'Add salt and mix everything gently.', duration: null },
      { stepNumber: 6, instruction: 'Serve immediately with tortilla chips.', duration: null },
    ],
  },
  {
    name: 'Bruschetta',
    category: 'Snacks',
    cookingTime: 15,
    difficulty: 'Easy',
    description: 'Toasted Italian bread topped with fresh tomatoes, basil, and a drizzle of olive oil.',
    servings: 4,
    imageColor: '#E57373',
    ingredients: [
      { name: 'Baguette or ciabatta', quantity: '1 loaf sliced', isRequired: 1, alternatives: 'Sourdough bread' },
      { name: 'Tomatoes', quantity: '4 medium diced', isRequired: 1, alternatives: null },
      { name: 'Fresh basil', quantity: '8-10 leaves', isRequired: 1, alternatives: 'Dried basil' },
      { name: 'Garlic', quantity: '2 cloves', isRequired: 1, alternatives: null },
      { name: 'Olive oil', quantity: '3 tbsp', isRequired: 1, alternatives: null },
      { name: 'Balsamic vinegar', quantity: '1 tbsp', isRequired: 0, alternatives: null },
      { name: 'Salt & pepper', quantity: 'To taste', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Dice tomatoes, chiffonade basil, and combine in a bowl.', duration: null },
      { stepNumber: 2, instruction: 'Add 2 tbsp olive oil, balsamic vinegar, salt, and pepper. Mix and let sit for 5 minutes.', duration: 5 },
      { stepNumber: 3, instruction: 'Slice bread into 1/2-inch thick pieces.', duration: null },
      { stepNumber: 4, instruction: 'Brush bread slices with remaining olive oil and toast in oven at 200°C for 5 minutes until golden.', duration: 5 },
      { stepNumber: 5, instruction: 'Rub the toasted bread with a cut garlic clove for flavor.', duration: null },
      { stepNumber: 6, instruction: 'Spoon the tomato-basil mixture generously onto each bread slice.', duration: null },
      { stepNumber: 7, instruction: 'Serve immediately as an appetizer or snack.', duration: null },
    ],
  },

  // ===== CAKES =====
  {
    name: 'Chocolate Lava Cake',
    category: 'Cakes',
    cookingTime: 25,
    difficulty: 'Medium',
    description: 'Decadent individual chocolate cakes with a warm, molten center. Pure indulgence.',
    servings: 2,
    imageColor: '#5D4037',
    ingredients: [
      { name: 'Dark chocolate', quantity: '100g', isRequired: 1, alternatives: 'Semi-sweet chocolate' },
      { name: 'Butter', quantity: '50g', isRequired: 1, alternatives: null },
      { name: 'Eggs', quantity: '2', isRequired: 1, alternatives: null },
      { name: 'Sugar', quantity: '1/4 cup', isRequired: 1, alternatives: 'Brown sugar' },
      { name: 'All-purpose flour', quantity: '2 tbsp', isRequired: 1, alternatives: null },
      { name: 'Vanilla extract', quantity: '1/2 tsp', isRequired: 0, alternatives: null },
      { name: 'Cocoa powder', quantity: 'For dusting', isRequired: 0, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Preheat oven to 200°C (390°F). Grease 2 ramekins with butter and dust with cocoa powder.', duration: null },
      { stepNumber: 2, instruction: 'Melt dark chocolate and butter together in a microwave (30-second intervals) or double boiler. Stir until smooth.', duration: 2 },
      { stepNumber: 3, instruction: 'Whisk eggs and sugar together in a separate bowl until pale and thick.', duration: 2 },
      { stepNumber: 4, instruction: 'Fold the melted chocolate mixture into the egg mixture gently.', duration: null },
      { stepNumber: 5, instruction: 'Sift in flour and fold until just combined — do not overmix.', duration: null },
      { stepNumber: 6, instruction: 'Pour batter evenly into the prepared ramekins.', duration: null },
      { stepNumber: 7, instruction: 'Bake for exactly 12-14 minutes — edges should be firm but the center should jiggle slightly.', duration: 14 },
      { stepNumber: 8, instruction: 'Let cool for 1 minute, then invert onto plates. Serve immediately — the center should ooze!', duration: 1 },
    ],
  },
  {
    name: 'Classic Vanilla Sponge',
    category: 'Cakes',
    cookingTime: 40,
    difficulty: 'Medium',
    description: 'Light and airy vanilla sponge cake — perfect as a base or enjoyed on its own with tea.',
    servings: 8,
    imageColor: '#FFF9C4',
    ingredients: [
      { name: 'All-purpose flour', quantity: '1.5 cups', isRequired: 1, alternatives: null },
      { name: 'Sugar', quantity: '3/4 cup', isRequired: 1, alternatives: null },
      { name: 'Eggs', quantity: '3', isRequired: 1, alternatives: null },
      { name: 'Butter', quantity: '100g melted', isRequired: 1, alternatives: 'Oil' },
      { name: 'Milk', quantity: '1/2 cup', isRequired: 1, alternatives: null },
      { name: 'Baking powder', quantity: '2 tsp', isRequired: 1, alternatives: null },
      { name: 'Vanilla extract', quantity: '1 tsp', isRequired: 1, alternatives: null },
      { name: 'Salt', quantity: 'A pinch', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Preheat oven to 180°C (350°F). Grease and line a round cake tin with parchment paper.', duration: null },
      { stepNumber: 2, instruction: 'Beat eggs and sugar together with an electric mixer until light and fluffy (about 4-5 minutes).', duration: 5 },
      { stepNumber: 3, instruction: 'Add vanilla extract and melted butter. Mix on low speed.', duration: null },
      { stepNumber: 4, instruction: 'Sift flour, baking powder, and salt together. Fold into the wet mixture in two additions, alternating with milk.', duration: null },
      { stepNumber: 5, instruction: 'Pour the batter into the prepared tin. Tap gently to remove air bubbles.', duration: null },
      { stepNumber: 6, instruction: 'Bake for 25-30 minutes until a toothpick inserted in the center comes out clean.', duration: 30 },
      { stepNumber: 7, instruction: 'Cool in the tin for 10 minutes, then transfer to a wire rack to cool completely.', duration: 10 },
      { stepNumber: 8, instruction: 'Dust with powdered sugar or frost with your favorite icing.', duration: null },
    ],
  },
  {
    name: 'Banana Bread',
    category: 'Cakes',
    cookingTime: 55,
    difficulty: 'Easy',
    description: 'Moist, tender banana bread with a beautiful golden crust. The riper the bananas, the better!',
    servings: 6,
    imageColor: '#C8A96E',
    ingredients: [
      { name: 'Ripe bananas', quantity: '3 large', isRequired: 1, alternatives: null },
      { name: 'All-purpose flour', quantity: '1.5 cups', isRequired: 1, alternatives: 'Wheat flour' },
      { name: 'Sugar', quantity: '1/2 cup', isRequired: 1, alternatives: 'Brown sugar, Honey' },
      { name: 'Butter', quantity: '1/3 cup melted', isRequired: 1, alternatives: 'Oil' },
      { name: 'Egg', quantity: '1', isRequired: 1, alternatives: null },
      { name: 'Baking soda', quantity: '1 tsp', isRequired: 1, alternatives: null },
      { name: 'Vanilla extract', quantity: '1 tsp', isRequired: 0, alternatives: null },
      { name: 'Walnuts', quantity: '1/3 cup chopped', isRequired: 0, alternatives: 'Pecans, Chocolate chips' },
      { name: 'Salt', quantity: 'A pinch', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Preheat oven to 175°C (350°F). Grease a loaf pan with butter or line with parchment.', duration: null },
      { stepNumber: 2, instruction: 'Mash ripe bananas in a large bowl until smooth with a few small chunks.', duration: null },
      { stepNumber: 3, instruction: 'Add melted butter, sugar, beaten egg, and vanilla. Mix until well combined.', duration: null },
      { stepNumber: 4, instruction: 'Add flour, baking soda, and salt. Fold gently until just combined — do not overmix.', duration: null },
      { stepNumber: 5, instruction: 'Fold in chopped walnuts if using.', duration: null },
      { stepNumber: 6, instruction: 'Pour batter into the prepared loaf pan and smooth the top.', duration: null },
      { stepNumber: 7, instruction: 'Bake for 50-55 minutes until the top is golden and a toothpick comes out clean.', duration: 55 },
      { stepNumber: 8, instruction: 'Cool in the pan for 10 minutes, then turn out onto a wire rack.', duration: 10 },
    ],
  },

  // ===== SALADS =====
  {
    name: 'Caesar Salad',
    category: 'Salads',
    cookingTime: 15,
    difficulty: 'Easy',
    description: 'Crisp romaine lettuce with creamy Caesar dressing, crunchy croutons, and shaved parmesan.',
    servings: 2,
    imageColor: '#AED581',
    ingredients: [
      { name: 'Romaine lettuce', quantity: '1 large head', isRequired: 1, alternatives: 'Iceberg lettuce' },
      { name: 'Croutons', quantity: '1 cup', isRequired: 1, alternatives: 'Toasted bread cubes' },
      { name: 'Parmesan cheese', quantity: '1/4 cup shaved', isRequired: 1, alternatives: null },
      { name: 'Caesar dressing', quantity: '4 tbsp', isRequired: 1, alternatives: null },
      { name: 'Lemon juice', quantity: '1 tbsp', isRequired: 0, alternatives: null },
      { name: 'Black pepper', quantity: 'To taste', isRequired: 0, alternatives: null },
      { name: 'Grilled chicken', quantity: '1 breast sliced', isRequired: 0, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Wash and dry romaine lettuce. Tear or chop into bite-sized pieces.', duration: null },
      { stepNumber: 2, instruction: 'If adding chicken, grill or pan-sear a chicken breast, let rest, then slice.', duration: 8 },
      { stepNumber: 3, instruction: 'Place lettuce in a large salad bowl.', duration: null },
      { stepNumber: 4, instruction: 'Drizzle Caesar dressing over the lettuce and toss well to coat evenly.', duration: null },
      { stepNumber: 5, instruction: 'Add croutons and sliced chicken on top.', duration: null },
      { stepNumber: 6, instruction: 'Finish with shaved parmesan, a squeeze of lemon, and freshly cracked black pepper.', duration: null },
      { stepNumber: 7, instruction: 'Serve immediately while the croutons are still crunchy.', duration: null },
    ],
  },
  {
    name: 'Greek Salad',
    category: 'Salads',
    cookingTime: 10,
    difficulty: 'Easy',
    description: 'A refreshing Mediterranean salad with chunky vegetables, feta cheese, and a lemon-olive oil dressing.',
    servings: 2,
    imageColor: '#64B5F6',
    ingredients: [
      { name: 'Cucumber', quantity: '1 large diced', isRequired: 1, alternatives: null },
      { name: 'Tomatoes', quantity: '2 medium diced', isRequired: 1, alternatives: 'Cherry tomatoes' },
      { name: 'Red onion', quantity: '1/2 sliced into rings', isRequired: 1, alternatives: null },
      { name: 'Feta cheese', quantity: '100g cubed', isRequired: 1, alternatives: 'Paneer' },
      { name: 'Kalamata olives', quantity: '1/4 cup', isRequired: 0, alternatives: 'Black olives' },
      { name: 'Olive oil', quantity: '2 tbsp', isRequired: 1, alternatives: null },
      { name: 'Lemon juice', quantity: '1 tbsp', isRequired: 1, alternatives: null },
      { name: 'Dried oregano', quantity: '1/2 tsp', isRequired: 0, alternatives: null },
      { name: 'Salt & pepper', quantity: 'To taste', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Dice cucumber and tomatoes into chunky pieces. Slice red onion into thin rings.', duration: null },
      { stepNumber: 2, instruction: 'Combine cucumber, tomatoes, red onion, and olives in a large bowl.', duration: null },
      { stepNumber: 3, instruction: 'Add cubed feta cheese on top.', duration: null },
      { stepNumber: 4, instruction: 'Whisk together olive oil, lemon juice, oregano, salt, and pepper in a small bowl.', duration: null },
      { stepNumber: 5, instruction: 'Drizzle the dressing over the salad.', duration: null },
      { stepNumber: 6, instruction: 'Toss gently so the feta stays in cubes, and serve fresh.', duration: null },
    ],
  },
  {
    name: 'Mango Avocado Salad',
    category: 'Salads',
    cookingTime: 10,
    difficulty: 'Easy',
    description: 'A tropical, vibrant salad combining sweet mango with creamy avocado and a zesty lime dressing.',
    servings: 2,
    imageColor: '#FFB74D',
    ingredients: [
      { name: 'Ripe mango', quantity: '1 large diced', isRequired: 1, alternatives: null },
      { name: 'Avocado', quantity: '1 large diced', isRequired: 1, alternatives: null },
      { name: 'Red bell pepper', quantity: '1/2 diced', isRequired: 0, alternatives: null },
      { name: 'Red onion', quantity: '2 tbsp finely diced', isRequired: 0, alternatives: null },
      { name: 'Fresh cilantro', quantity: '2 tbsp chopped', isRequired: 0, alternatives: 'Mint' },
      { name: 'Lime', quantity: '1', isRequired: 1, alternatives: 'Lemon' },
      { name: 'Olive oil', quantity: '1 tbsp', isRequired: 0, alternatives: null },
      { name: 'Salt', quantity: 'To taste', isRequired: 1, alternatives: null },
      { name: 'Chili flakes', quantity: 'A pinch', isRequired: 0, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Dice mango and avocado into similar-sized cubes.', duration: null },
      { stepNumber: 2, instruction: 'Dice red bell pepper and finely chop red onion and cilantro.', duration: null },
      { stepNumber: 3, instruction: 'Combine all the diced ingredients in a bowl.', duration: null },
      { stepNumber: 4, instruction: 'Squeeze fresh lime juice over the salad.', duration: null },
      { stepNumber: 5, instruction: 'Drizzle with olive oil, add salt and chili flakes.', duration: null },
      { stepNumber: 6, instruction: 'Toss gently and serve immediately — avocado browns quickly!', duration: null },
    ],
  },

  // ===== EXTRA RECIPES FOR VARIETY =====
  {
    name: 'Masala Omelette',
    category: 'Breakfast',
    cookingTime: 10,
    difficulty: 'Easy',
    description: 'Spiced Indian-style omelette loaded with onions, tomatoes, and green chilies. A spicy morning kick!',
    servings: 1,
    imageColor: '#FFD54F',
    ingredients: [
      { name: 'Eggs', quantity: '2', isRequired: 1, alternatives: null },
      { name: 'Onion', quantity: '1 small diced', isRequired: 1, alternatives: null },
      { name: 'Tomato', quantity: '1 small diced', isRequired: 1, alternatives: null },
      { name: 'Green chili', quantity: '1 chopped', isRequired: 0, alternatives: null },
      { name: 'Coriander leaves', quantity: '1 tbsp', isRequired: 0, alternatives: null },
      { name: 'Turmeric', quantity: '1/4 tsp', isRequired: 0, alternatives: null },
      { name: 'Salt & pepper', quantity: 'To taste', isRequired: 1, alternatives: null },
      { name: 'Oil or butter', quantity: '1 tbsp', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Beat eggs in a bowl. Add diced onion, tomato, green chili, coriander, turmeric, salt, and pepper.', duration: null },
      { stepNumber: 2, instruction: 'Heat oil or butter in a non-stick pan over medium heat.', duration: 1 },
      { stepNumber: 3, instruction: 'Pour the egg mixture into the pan and spread evenly.', duration: null },
      { stepNumber: 4, instruction: 'Cook on medium-low heat until the bottom is set and golden.', duration: 3 },
      { stepNumber: 5, instruction: 'Flip carefully and cook the other side for 1-2 minutes.', duration: 2 },
      { stepNumber: 6, instruction: 'Fold in half and serve hot with toast or paratha.', duration: null },
    ],
  },
  {
    name: 'Shakshuka',
    category: 'Lunch',
    cookingTime: 30,
    difficulty: 'Medium',
    description: 'Eggs poached in a spiced tomato sauce with bell peppers and onions. A hearty North African classic.',
    servings: 2,
    imageColor: '#E64A19',
    ingredients: [
      { name: 'Eggs', quantity: '4', isRequired: 1, alternatives: null },
      { name: 'Canned tomatoes', quantity: '400g', isRequired: 1, alternatives: 'Fresh tomatoes blended' },
      { name: 'Onion', quantity: '1 diced', isRequired: 1, alternatives: null },
      { name: 'Bell pepper', quantity: '1 diced', isRequired: 1, alternatives: null },
      { name: 'Garlic', quantity: '3 cloves minced', isRequired: 1, alternatives: null },
      { name: 'Cumin', quantity: '1 tsp', isRequired: 1, alternatives: null },
      { name: 'Paprika', quantity: '1 tsp', isRequired: 1, alternatives: null },
      { name: 'Chili flakes', quantity: '1/2 tsp', isRequired: 0, alternatives: null },
      { name: 'Olive oil', quantity: '2 tbsp', isRequired: 1, alternatives: null },
      { name: 'Feta cheese', quantity: '50g crumbled', isRequired: 0, alternatives: null },
      { name: 'Fresh parsley', quantity: 'For garnish', isRequired: 0, alternatives: 'Cilantro' },
      { name: 'Salt', quantity: 'To taste', isRequired: 1, alternatives: null },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Heat olive oil in a deep skillet over medium heat.', duration: 1 },
      { stepNumber: 2, instruction: 'Add diced onion and bell pepper. Sauté until softened, about 5 minutes.', duration: 5 },
      { stepNumber: 3, instruction: 'Add minced garlic, cumin, paprika, and chili flakes. Cook for 1 minute until fragrant.', duration: 1 },
      { stepNumber: 4, instruction: 'Pour in canned tomatoes. Stir well, season with salt, and simmer for 10 minutes until sauce thickens.', duration: 10 },
      { stepNumber: 5, instruction: 'Make 4 wells in the sauce using the back of a spoon.', duration: null },
      { stepNumber: 6, instruction: 'Crack an egg into each well. Cover the pan with a lid.', duration: null },
      { stepNumber: 7, instruction: 'Cook for 5-7 minutes until egg whites are set but yolks are still runny.', duration: 7 },
      { stepNumber: 8, instruction: 'Crumble feta on top, garnish with parsley, and serve with crusty bread.', duration: null },
    ],
  },
];

export default SEED_RECIPES;
